import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import test from 'node:test';

test('platform settings and audit history use real PostgreSQL permissions and triggers', async t => {
    const sql = await readFile(new URL('../supabase/migrations/20261010120000_platform_operations.sql', import.meta.url), 'utf8');
    let PGlite;
    try {
        ({ PGlite } = await import(process.env.PGLITE_TEST_MODULE || pathToFileURL(join(process.env.TEMP || '/tmp', 'kryin-operations-test/node_modules/@electric-sql/pglite/dist/index.js')).href));
    } catch { return t.skip('Set PGLITE_TEST_MODULE to a temporary @electric-sql/pglite installation to run the isolated PostgreSQL test.'); }
    const db = new PGlite();
    try {
        await db.exec(`
            CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
            CREATE SCHEMA auth;
            CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
            CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT coalesce(nullif(current_setting('request.jwt.claim.role',true),''),'authenticated') $$;
            CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql AS $$ SELECT coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
            CREATE TABLE public.schools(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,status text DEFAULT 'active',deleted_at timestamptz,ai_connections_enabled boolean DEFAULT false);
            CREATE TABLE public.profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),full_name text,role text,school_id uuid,is_active boolean DEFAULT true,deleted_at timestamptz,metadata jsonb,email text,login_id text);
            CREATE TABLE auth.sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,ip inet,user_agent text);
            CREATE FUNCTION public.get_auth_role() RETURNS text LANGUAGE sql SECURITY DEFINER AS $$ SELECT role FROM public.profiles WHERE id=auth.uid() $$;
            CREATE FUNCTION public.get_auth_school_id() RETURNS uuid LANGUAGE sql SECURITY DEFINER AS $$ SELECT school_id FROM public.profiles WHERE id=auth.uid() $$;
            CREATE FUNCTION public.has_role(p_id uuid,p_role text) RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=p_id AND role=p_role AND is_active AND deleted_at IS NULL) $$;
            CREATE TABLE public.classes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,name text,deleted_at timestamptz);
            CREATE TABLE public.announcements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,title text,body text,deleted_at timestamptz);
            CREATE TABLE public.user_roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,role text);
            CREATE TABLE public.admin_action_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,actor_id uuid,actor_role text,school_id uuid,target_user_id uuid,action text,detail jsonb,created_at timestamptz DEFAULT now());
            CREATE TABLE public.system_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,user_id uuid,action text,message text,category text,level text,status text,details jsonb,ip_address text,user_agent text,created_at timestamptz DEFAULT now());
            CREATE TABLE public.system_alerts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,title text,message text,severity text,category text,is_resolved boolean DEFAULT false,resolved_by uuid,resolved_at timestamptz,created_at timestamptz DEFAULT now());
            CREATE TABLE public.dashboard_metrics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,metric_key text,metric_value numeric,previous_value numeric,updated_at timestamptz DEFAULT now());
            CREATE TABLE public.employees(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,deleted_at timestamptz);
            CREATE TABLE public.transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,type text,status text,amount numeric,created_at timestamptz DEFAULT now());
            CREATE TABLE public.invoices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,status text,amount numeric,deleted_at timestamptz,created_at timestamptz DEFAULT now());
            CREATE TABLE public.school_subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_id uuid,status text);
            GRANT USAGE ON SCHEMA public,auth TO authenticated,service_role;
            GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated,service_role;
            INSERT INTO schools(id,name) VALUES('10000000-0000-0000-0000-000000000001','Alpha'),('10000000-0000-0000-0000-000000000002','Beta');
            INSERT INTO profiles(id,full_name,role,school_id) VALUES
              ('20000000-0000-0000-0000-000000000001','Owner','superadmin',NULL),
              ('20000000-0000-0000-0000-000000000002','Alice','admin','10000000-0000-0000-0000-000000000001'),
              ('20000000-0000-0000-0000-000000000003','Bob','admin','10000000-0000-0000-0000-000000000002');
        `);
        await db.exec(sql);
        await db.exec(await readFile(new URL('../supabase/migrations/20261010123000_auth_session_activity.sql', import.meta.url),'utf8'));
        await db.exec(await readFile(new URL('../supabase/migrations/20261010124500_activity_outcomes.sql', import.meta.url),'utf8'));
        const actor = async (id, role = 'authenticated', headers = {}) => {
            await db.exec('RESET ROLE');
            await db.query("SELECT set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false),set_config('request.headers',$3,false)", [id,role,JSON.stringify(headers)]);
            await db.query("SELECT set_config('request.jwt.claims','{}',false)");
            await db.exec(`SET ROLE ${role}`);
        };
        const owner = '20000000-0000-0000-0000-000000000001';
        const alice = '20000000-0000-0000-0000-000000000002';
        const school = '10000000-0000-0000-0000-000000000001';
        await actor(owner);
        const settings = (await db.query('SELECT public.fn_get_platform_settings() AS settings')).rows[0].settings;
        assert.equal(settings.maintenance_enabled, false);
        await db.query("SELECT public.fn_update_platform_settings($1::jsonb)", [JSON.stringify({maintenance_enabled:false,maintenance_message:'Scheduled updates',support_email:'ops@example.com',metrics_stale_minutes:60})]);
        await assert.rejects(db.query("SELECT public.fn_update_platform_settings('{\"metrics_stale_minutes\":0}')"), /between|invalid/i);
        await assert.rejects(db.query("SELECT public.fn_update_platform_settings('{\"unimplemented\":true}')"), /unknown|unsupported/i);
        await actor(alice, 'authenticated', {'x-kryin-actor-id': owner});
        await assert.rejects(db.query('SELECT public.fn_get_platform_settings()'), /superadmin/i);
        await assert.rejects(db.query("SELECT public.fn_update_platform_settings('{\"maintenance_enabled\":true}')"), /superadmin/i);
        const c = (await db.query('INSERT INTO classes(school_id,name) VALUES($1,$2) RETURNING id',[school,'Grade 6'])).rows[0].id;
        await db.query('UPDATE classes SET name=$2 WHERE id=$1',[c,'Grade 7']);
        await db.query('DELETE FROM classes WHERE id=$1',[c]);
        await db.query('INSERT INTO announcements(school_id,title,body) VALUES($1,$2,$3)', [school,'Assembly','Tomorrow']);
        await db.query('INSERT INTO admin_action_audit(actor_id,school_id,action) VALUES($1,$2,$3)',[alice,school,'user_hard_delete_failed']);
        await db.query('UPDATE profiles SET metadata=$2::jsonb WHERE id=$1', [alice,JSON.stringify({password:'never store',nested:{staff_pin_hash:'secret',note:'kept'}})]);
        let feed = (await db.query('SELECT public.fn_get_system_activity() AS feed')).rows[0].feed;
        const deleted = feed.find(e => e.details?.record_id === c && e.action === 'classes.delete');
        assert.equal(deleted.user_name, 'Alice');
        assert.equal(deleted.details.old_data.name, 'Grade 7');
        assert.equal(deleted.details.source, 'authenticated_request');
        const edited = feed.find(e => e.action === 'profiles.update');
        assert.equal(feed.find(e=>e.action==='user_hard_delete_failed').status,'failed');
        assert.equal(feed.find(e=>e.action==='user_hard_delete_failed').level,'error');
        assert.equal(edited.details.new_data.metadata.password, '[REDACTED]');
        assert.equal(edited.details.new_data.metadata.nested.staff_pin_hash, '[REDACTED]');
        assert.equal(edited.details.new_data.metadata.nested.note, 'kept');
        await assert.rejects(db.query("DELETE FROM public.system_activity_events"), /permission|denied/i);
        await actor('20000000-0000-0000-0000-000000000003');
        assert.equal((await db.query('SELECT public.fn_get_system_activity() AS feed')).rows[0].feed.length, 0);
        await actor(owner);
        await db.query("INSERT INTO system_alerts(title,message,severity,category) VALUES('Platform maintenance mode enabled','Old message','warning','maintenance'),('Dashboard metrics are stale','Old number','critical','metrics')");
        await db.query('SELECT public.refresh_dashboard_metrics()');
        await db.query('SELECT public.fn_reconcile_system_alerts()');
        assert.equal((await db.query('SELECT count(*)::int AS n FROM system_alerts WHERE NOT is_resolved')).rows[0].n, 0);
        await db.query("SELECT public.fn_update_platform_settings('{\"maintenance_enabled\":true}')");
        await actor(alice);
        await assert.rejects(db.query('INSERT INTO classes(school_id,name) VALUES($1,$2)',[school,'Blocked']), /maintenance/i);
        await actor('', 'service_role', {'x-kryin-actor-id':alice});
        await assert.rejects(db.query('INSERT INTO classes(school_id,name) VALUES($1,$2)',[school,'Also blocked']), /maintenance/i);
        await actor(owner);
        await db.query("SELECT public.fn_update_platform_settings('{\"maintenance_enabled\":false}')");
        await actor('', 'service_role', {'x-kryin-actor-id':alice});
        const serverClass = (await db.query('INSERT INTO classes(school_id,name) VALUES($1,$2) RETURNING id',[school,'Via edge'])).rows[0].id;
        await actor(owner);
        feed = (await db.query('SELECT public.fn_get_system_activity() AS feed')).rows[0].feed;
        assert.equal(feed.find(e => e.details?.record_id === serverClass).user_name, 'Alice');
        await db.exec('RESET ROLE');
        const session = (await db.query("INSERT INTO auth.sessions(user_id,ip,user_agent) VALUES($1,'127.0.0.1','Test browser') RETURNING id",[alice])).rows[0].id;
        await db.query('DELETE FROM auth.sessions WHERE id=$1',[session]);
        await actor(owner);
        feed = (await db.query('SELECT public.fn_get_system_activity() AS feed')).rows[0].feed;
        assert.equal(feed.find(e => e.action==='auth.session_started').user_name,'Alice');
        assert.equal(feed.find(e => e.action==='auth.session_started').ip_address,'127.0.0.1');
        assert.equal(feed.find(e => e.action==='auth.session_ended').details.source,'auth_service');
        await db.query('DELETE FROM profiles WHERE id=$1',[alice]);
        feed = (await db.query('SELECT public.fn_get_system_activity() AS feed')).rows[0].feed;
        assert.equal(feed.find(e => e.details?.record_id === c && e.action === 'classes.delete').user_name, 'Alice');
        await db.query('SELECT public.refresh_dashboard_metrics()');
        await db.query('SELECT public.refresh_dashboard_metrics()');
        assert.equal((await db.query("SELECT count(*)::int AS n FROM dashboard_metrics WHERE school_id IS NULL AND metric_key='total_schools'")).rows[0].n, 1);
        await db.exec('RESET ROLE');
        await db.exec(`ALTER TABLE schools ADD COLUMN max_students integer DEFAULT 100, ADD COLUMN subscription_status text DEFAULT 'active';
          CREATE SCHEMA storage;
          CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean DEFAULT false,file_size_limit bigint);
          CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text,owner uuid,owner_id text,metadata jsonb,user_metadata jsonb,created_at timestamptz DEFAULT now());
          INSERT INTO storage.buckets VALUES('announcement-images','Announcement images',false,5242880);
          INSERT INTO storage.objects(bucket_id,name,metadata) VALUES('announcement-images','${school}/image.png','{"size":4096}'),('announcement-images','unknown/file.png','{}');`);
        // Validate health against the actual business schema, not fixture-only columns.
        await db.exec(await readFile(new URL('../supabase/migrations/20261010130000_maintenance_health.sql', import.meta.url),'utf8'));
        await db.exec(await readFile(new URL('../supabase/migrations/20261010133000_maintenance_edge_guard.sql', import.meta.url),'utf8'));
        await actor('', 'anon');
        assert.equal((await db.query('SELECT fn_platform_status() AS s')).rows[0].s.maintenance_enabled, false);
        await assert.rejects(db.query('SELECT fn_platform_health_console()'), /permission|denied/i);
        await actor(owner);
        let consoleHealth = (await db.query('SELECT fn_platform_health_console() AS h')).rows[0].h;
        assert.equal(consoleHealth.storage.files, 2);
        assert.equal(consoleHealth.storage.unknown_size_files, 1);
        assert.equal(consoleHealth.school_details.find(s => s.id === school).file_bytes, 4096);
        assert.ok(consoleHealth.database.size_bytes > 0);
        assert.ok(consoleHealth.tables.some(t => t.name === 'classes'));
        await assert.rejects(db.query('SELECT fn_record_request_metrics(3,4,10)'), /invalid/i);
        await actor('20000000-0000-0000-0000-000000000003');
        await db.query('SELECT fn_record_request_metrics(3,1,120)');
        await assert.rejects(db.query('SELECT fn_platform_health_console()'), /superadmin/i);
        await actor(owner);
        consoleHealth = (await db.query('SELECT fn_platform_health_console() AS h')).rows[0].h;
        assert.equal(consoleHealth.requests.requests, 3);
        assert.equal(consoleHealth.requests.failures, 1);
        assert.equal(consoleHealth.school_details.find(s => s.name === 'Beta').requests, 3);
        assert.equal(consoleHealth.school_details.find(s => s.name === 'Alpha').requests, 0);
        const schoolHealth = (await db.query('SELECT fn_school_health($1) AS h', [school])).rows[0].h;
        assert.ok(schoolHealth.tables.find(t => t.name === 'classes').rows > 0);
        assert.ok(schoolHealth.logical_bytes > 0);
        await db.query("SELECT fn_update_platform_settings('{\"maintenance_enabled\":true}')");
        await db.query('SELECT fn_check_platform_access()');
        await actor('20000000-0000-0000-0000-000000000003');
        await assert.rejects(db.query('SELECT fn_check_platform_access()'), /maintenance/i);
        await db.exec('RESET ROLE');
        await db.exec(await readFile(new URL('../supabase/migrations/20261010140000_cache_cleanup.sql', import.meta.url),'utf8'));
        await actor('', 'anon');
        await assert.rejects(db.query('SELECT fn_cleanup_request_metrics()'), /permission|denied/i);
        await assert.rejects(db.query('SELECT fn_platform_cache_status()'), /permission|denied/i);
        await actor(owner);
        await db.exec('RESET ROLE');
        await db.query("INSERT INTO app_request_metrics(user_id,school_id,minute,requests) VALUES($1,$2,now()-interval '8 days',5),($1,$2,now()-interval '2 days',7)", [owner,school]);
        await actor('20000000-0000-0000-0000-000000000003');
        await assert.rejects(db.query('SELECT fn_cleanup_request_metrics()'), /superadmin/i);
        await actor(owner);
        const cleanupStatus = (await db.query('SELECT fn_platform_cache_status() AS s')).rows[0].s;
        assert.equal(cleanupStatus.expired_rows, 1);
        assert.ok(cleanupStatus.expired_logical_bytes > 0);
        assert.equal((await db.query('SELECT fn_cleanup_request_metrics() AS s')).rows[0].s.removed_rows, 1);
        assert.equal((await db.query('SELECT fn_platform_cache_status() AS s')).rows[0].s.expired_rows, 0);
        assert.equal((await db.query('SELECT fn_cleanup_request_metrics() AS s')).rows[0].s.removed_rows, 0);
        await db.exec('RESET ROLE');
        assert.equal((await db.query('SELECT count(*)::int n FROM app_request_metrics WHERE minute>now()-interval \'7 days\'')).rows[0].n, 2);
        await actor(owner);
        const cleanupFeed = (await db.query('SELECT fn_get_system_activity() AS f')).rows[0].f;
        assert.equal(cleanupFeed.find(e => e.action === 'cache.expired_requests_cleanup').user_name, 'Owner');
        await db.exec('RESET ROLE');
        await db.exec("UPDATE profiles SET email=lower(full_name)||'@example.test',login_id=lower(full_name)");
        await db.exec(await readFile(new URL('../supabase/migrations/20261010150000_activity_context.sql', import.meta.url),'utf8'));
        const bob = '20000000-0000-0000-0000-000000000003';
        const beta = '10000000-0000-0000-0000-000000000002';
        const browserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/154.0.0.0 Safari/537.36';
        const bobSession = (await db.query("INSERT INTO auth.sessions(user_id,ip,user_agent) VALUES($1,'198.51.100.7','Firefox/144.0') RETURNING id",[bob])).rows[0].id;
        await actor(bob, 'authenticated', {'user-agent':browserAgent,'x-kryin-actor-id':owner,'x-kryin-user-agent':'Spoofed agent'});
        await db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({ session_id:bobSession })]);
        await db.query("SELECT fn_record_client_event('test.browser_context','Real actor context','system','info','success',$1)",[JSON.stringify({user_email:'fake@example.test',user_username:'owner'})]);
        const contextFeed = (await db.query('SELECT fn_get_system_activity(p_school=>$1) AS f',[school])).rows[0].f;
        assert.ok(contextFeed.every(e => e.school_id === beta), 'identity context does not widen tenant scope');
        const browserEvent = contextFeed.find(e => e.action === 'test.browser_context');
        assert.equal(browserEvent.user_email,'bob@example.test');
        assert.equal(browserEvent.user_username,'bob');
        assert.equal(browserEvent.identity_source,'event_snapshot');
        assert.equal(browserEvent.user_agent,browserAgent);
        assert.equal(browserEvent.ip_address,'198.51.100.7');
        assert.equal(browserEvent.ip_address_source,'auth_session');
        await actor(owner);
        await db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({session_id:bobSession})]);
        await db.query("SELECT fn_record_client_event('test.mismatched_session','Cannot borrow another session')");
        let contextual = (await db.query('SELECT fn_get_system_activity() AS f')).rows[0].f;
        assert.equal(contextual.find(e => e.action === 'test.mismatched_session').ip_address,null);
        assert.equal(contextual.find(e => e.action === 'cache.expired_requests_cleanup').identity_source,'profile_backfill');
        await actor('', 'service_role', {'x-kryin-actor-id':bob,'x-kryin-session-id':bobSession,'x-kryin-user-agent':browserAgent+' OPR/124.0'});
        await db.query("INSERT INTO system_activity_events(user_id,school_id,action,message,category,user_agent) VALUES($1,$2,'test.edge_context','Verified edge actor','system','Deno/2.1')",[bob,beta]);
        await actor(owner);
        contextual = (await db.query('SELECT fn_get_system_activity() AS f')).rows[0].f;
        assert.equal(contextual.find(e => e.action === 'test.edge_context').user_agent,browserAgent+' OPR/124.0');
        assert.equal(contextual.find(e => e.action === 'test.edge_context').ip_address,'198.51.100.7');
        await db.query("UPDATE profiles SET email='changed@example.test',login_id='changed' WHERE id=$1",[bob]);
        await db.query('DELETE FROM profiles WHERE id=$1',[bob]);
        contextual = (await db.query("SELECT fn_get_system_activity(p_search=>'bob@example.test') AS f")).rows[0].f;
        assert.equal(contextual.find(e => e.action === 'test.browser_context').user_email,'bob@example.test');
        assert.equal(contextual.find(e => e.action === 'test.browser_context').user_username,'bob');
    } finally { await db.close(); }
});
