import { useEffect, useMemo, useState } from 'react';
import Sidebar from '../components/dashboard/Sidebar';
import Header from '../components/dashboard/Header';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

type ClassItem = { id: string; name: string }; type TestItem = { id: string; name: string; classId: string; className: string }; type SubjectItem = { id: string; subjectId: string; name: string; maxMarks: number }; type Student = { id: string; full_name: string | null; email: string | null };
export default function MarksEntry() {
  const { user, roles, role } = useAuth();
  const [classes, setClasses] = useState<ClassItem[]>([]);
  const [tests, setTests] = useState<TestItem[]>([]);
  const [testId, setTestId] = useState('');
  const [subjects, setSubjects] = useState<SubjectItem[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [marks, setMarks] = useState<Record<string, string>>({});
  const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false);

  const isElevatedAdmin = roles.includes('admin') || roles.includes('superadmin');

  useEffect(() => {
    if (!user?.schoolId) return;
    let query = supabase.from('classes').select('id,name').eq('school_id', user.schoolId).is('deleted_at', null).order('name');
    // Phase 15: Authoritative role check - non-admins are strictly scoped to their assigned classes
    if (!isElevatedAdmin || role === 'teacher') {
      query = query.eq('teacher_id', user.id);
    }
    query.then(({ data }) => setClasses((data ?? []) as ClassItem[]));
  }, [role, roles, isElevatedAdmin, user?.id, user?.schoolId]);
  useEffect(() => { const load = async () => { if (!user?.schoolId) return; const { data: rows } = await supabase.from('exam_subjects').select('exam_id,class_id').eq('school_id', user.schoolId).is('deleted_at', null); const allowed = new Set(classes.map(item => item.id)); const unique = [...new Map((rows ?? []).filter(row => allowed.has(row.class_id)).map(row => [row.exam_id, row])).values()]; if (!unique.length) return setTests([]); const [{ data: examRows }, { data: classRows }] = await Promise.all([supabase.from('exams').select('id,name').in('id', unique.map(row => row.exam_id)).is('deleted_at', null).order('start_date', { ascending: false }), supabase.from('classes').select('id,name').in('id', unique.map(row => row.class_id))]); const examNames = new Map((examRows ?? []).map(row => [row.id, row.name])); const classNames = new Map((classRows ?? []).map(row => [row.id, row.name])); setTests(unique.filter(row => examNames.has(row.exam_id)).map(row => ({ id: row.exam_id, name: examNames.get(row.exam_id)!, classId: row.class_id, className: classNames.get(row.class_id) || 'Class' }))); }; load(); }, [classes, user?.schoolId]);
  const activeTest = useMemo(() => tests.find(test => test.id === testId), [testId, tests]);
  useEffect(() => { const load = async () => { setSubjects([]); setStudents([]); setMarks({}); if (!activeTest || !user?.schoolId) return; const [{ data: examSubjects }, { data: enrollment }] = await Promise.all([supabase.from('exam_subjects').select('id,subject_id,max_marks').eq('exam_id', activeTest.id).eq('class_id', activeTest.classId).is('deleted_at', null), supabase.from('class_enrollments').select('student_id').eq('class_id', activeTest.classId).is('deleted_at', null)]); const subjectRows = examSubjects ?? []; const ids = subjectRows.map(row => row.subject_id); const studentIds = (enrollment ?? []).map(row => row.student_id); const [{ data: subjectRowsData }, { data: profileRows }, { data: resultRows }] = await Promise.all([ids.length ? supabase.from('subjects').select('id,name').in('id', ids) : Promise.resolve({ data: [] as { id: string; name: string }[] }), studentIds.length ? supabase.from('profiles').select('id,full_name,email').in('id', studentIds).is('deleted_at', null).order('full_name') : Promise.resolve({ data: [] as Student[] }), subjectRows.length ? supabase.from('exam_results').select('id,student_id,exam_subject_id,marks_obtained').in('exam_subject_id', subjectRows.map(row => row.id)).is('deleted_at', null) : Promise.resolve({ data: [] as { id: string; student_id: string; exam_subject_id: string; marks_obtained: number | null }[] })]); const names = new Map(((subjectRowsData ?? []) as { id: string; name: string }[]).map((row: { id: string; name: string }) => [row.id, row.name])); setSubjects(subjectRows.map(row => ({ id: row.id, subjectId: row.subject_id, name: names.get(row.subject_id) || 'Subject', maxMarks: row.max_marks }))); setStudents((profileRows ?? []) as Student[]); setMarks(Object.fromEntries(((resultRows ?? []) as { student_id: string; exam_subject_id: string; marks_obtained: number | null }[]).map(row => [`${row.student_id}:${row.exam_subject_id}`, row.marks_obtained?.toString() || '']))); }; load(); }, [activeTest, user?.schoolId]);
  const save = async () => { if (!user?.schoolId || !subjects.length) return; setSaving(true); const existing = await supabase.from('exam_results').select('id,student_id,exam_subject_id').in('exam_subject_id', subjects.map(subject => subject.id)).is('deleted_at', null); const byKey = new Map((existing.data ?? []).map(row => [`${row.student_id}:${row.exam_subject_id}`, row.id])); const writes = Object.entries(marks).filter(([, value]) => value.trim() !== '').map(async ([key, value]) => { const [student_id, exam_subject_id] = key.split(':'); const data = { marks_obtained: Number(value), graded_by: user.id }; const id = byKey.get(key); return id ? supabase.from('exam_results').update(data).eq('id', id) : supabase.from('exam_results').insert({ ...data, school_id: user.schoolId!, student_id, exam_subject_id }); }); const results = await Promise.all(writes); setSaving(false); const error = results.find(result => result.error)?.error; setMessage(error ? error.message : `Saved ${writes.length} mark(s).`); };
  return <div className="flex min-h-screen bg-background"><Sidebar activePage="Marks" /><div className="flex min-h-screen flex-1 flex-col lg:ml-72"><Header title="Upload marks" /><main className="flex-1 space-y-7 overflow-y-auto p-5 pb-24 sm:p-8"><section className="clay-card p-6 sm:p-8"><p className="text-sm font-bold text-primary">Admin and teacher tools</p><h1 className="mt-1 text-3xl font-bold text-foreground">Upload test marks</h1><p className="mt-2 text-muted">Choose a created test. Its class, subjects and students are loaded automatically.</p><label className="mt-6 grid max-w-xl gap-2 text-sm font-bold text-foreground"><span>Test</span><select value={testId} onChange={event => setTestId(event.target.value)} className="rounded-xl border border-border bg-white px-3 py-2.5"><option value="">Choose test</option>{tests.map(test => <option key={test.id} value={test.id}>{test.name} — {test.className}</option>)}</select></label></section><section className="clay-card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-6 py-4"><div><h2 className="font-bold text-foreground">Student marks{activeTest ? ` · ${activeTest.className}` : ''}</h2><p className="mt-1 text-sm text-muted">Enter marks for every selected test subject, then save.</p></div><button type="button" onClick={save} disabled={saving || !testId} className="rounded-xl bg-foreground px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Save marks</button></div>{students.length && subjects.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="border-b border-border bg-stone-50 text-xs uppercase tracking-wider text-muted"><tr><th className="px-6 py-3">Student</th>{subjects.map(subject => <th key={subject.id} className="px-4 py-3">{subject.name}<span className="block normal-case tracking-normal">/ {subject.maxMarks}</span></th>)}</tr></thead><tbody className="divide-y divide-border">{students.map(student => <tr key={student.id}><td className="px-6 py-3"><b className="block text-foreground">{student.full_name || student.email}</b><small className="text-muted">{student.email}</small></td>{subjects.map(subject => { const key = `${student.id}:${subject.id}`; return <td key={subject.id} className="px-4 py-3"><input type="number" min="0" max={subject.maxMarks} value={marks[key] || ''} onChange={event => setMarks(current => ({ ...current, [key]: event.target.value }))} className="w-24 rounded-xl border border-border bg-white px-3 py-2 text-right" placeholder="—" /></td>; })}</tr>)}</tbody></table></div> : <p className="p-6 text-muted">Choose a test to load its students and subjects.</p>}{message && <p className="border-t border-border px-6 py-3 text-sm font-medium text-muted">{message}</p>}</section></main></div></div>;
}
