import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Activity, RefreshCw, ExternalLink } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { reconcileAlerts } from '../../lib/operations';
import { filesystemUsed } from '../../lib/healthUsage';
import UsageMeter from './UsageMeter';
import CacheCleanup from './CacheCleanup';
import type { HealthConsoleData, SchoolHealthDetail } from '../../lib/operations';

const count = (value: number | null | undefined) => value == null ? 'Unavailable' : value.toLocaleString();
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : 'Not recorded';
const bytes = (value: number | null | undefined) => {
    if (value == null) return 'Unavailable';
    if (value === 0) return '0 B';
    const unit = Math.min(4, Math.max(0, Math.floor(Math.log(value) / Math.log(1024))));
    return `${(value / 1024 ** unit).toLocaleString(undefined, { maximumFractionDigits: 2 })} ${['B', 'KiB', 'MiB', 'GiB', 'TiB'][unit]}`;
};
const ms = (value: number | null) => value == null ? 'No samples' : `${value.toLocaleString()} ms`;
const cell = 'border-b border-stone-100 px-3 py-3 text-left align-top';
function Stat({ label, value, hint, used, total, basis, unavailable, showRemaining }: { label: string; value: string | number; hint?: string; used?: number | null; total?: number | null; basis?: string; unavailable?: string; showRemaining?: boolean }) {
    return <div className="rounded-xl border border-stone-200 bg-white p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 break-words text-xl font-bold tabular-nums">{value}</p>{hint && <p className="mt-2 text-xs text-muted">{hint}</p>}{basis && <UsageMeter used={used} total={total} basis={basis} unavailable={unavailable} showRemaining={showRemaining} />}</div>;
}

async function browserStorage() {
    const estimate = await navigator.storage?.estimate?.().catch(() => null);
    let localBytes: number | null = null, sessionBytes: number | null = null;
    for (const [storage, assign] of [[localStorage, (n: number) => { localBytes = n; }], [sessionStorage, (n: number) => { sessionBytes = n; }]] as const) {
        try { let total = 0; for (let i = 0; i < storage.length; i++) { const key = storage.key(i) ?? ''; total += (key.length + (storage.getItem(key)?.length ?? 0)) * 2; } assign(total); } catch { /* Browser policy may deny access. */ }
    }
    let cacheEntries: number | null = null;
    if ('caches' in window) { try { cacheEntries = 0; for (const name of await caches.keys()) cacheEntries += (await (await caches.open(name)).keys()).length; } catch { /* No cache access. */ } }
    return { originBytes: estimate?.usage, quotaBytes: estimate?.quota, localBytes, sessionBytes, cacheEntries };
}

export default function HealthConsole() {
    const queryClient = useQueryClient();
    const [schoolId, setSchoolId] = useState('');
    const [search, setSearch] = useState('');
    const [section, setSection] = useState('Overview');
    const project = new URL(import.meta.env.VITE_SUPABASE_URL).hostname.split('.')[0];
    const health = useQuery({ queryKey: ['platform-health-console'], refetchInterval: 30_000, refetchOnWindowFocus: true,
        queryFn: async () => {
            await reconcileAlerts();
            const started = performance.now();
            const { data, error } = await supabase.rpc('fn_platform_health_console'); if (error) throw error;
            return { ...(data as HealthConsoleData), roundtrip_ms: Math.round(performance.now() - started) };
        },
    });
    const schoolDetail = useQuery({ queryKey: ['school-health', schoolId], enabled: !!schoolId && section === 'Schools', refetchInterval: 60_000,
        queryFn: async () => { const { data, error } = await supabase.rpc('fn_school_health', { p_school: schoolId }); if (error) throw error; return data as SchoolHealthDetail; },
    });
    const browser = useQuery({ queryKey: ['browser-storage-health'], queryFn: browserStorage, refetchInterval: 30_000 });
    const h = health.data;
    const dataVolume = h?.infrastructure?.filesystems.find(f => f.mount === '/data');
    const school = h?.school_details.find(s => s.id === schoolId);
    const refresh = () => Promise.all([health.refetch(), browser.refetch(), schoolId && section === 'Schools' ? schoolDetail.refetch() : Promise.resolve()]);
    const external = (path: string, label: string) => <a href={`https://supabase.com/dashboard/project/${project}${path}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-primary underline">{label}<ExternalLink size={14} /></a>;

    return <div className="space-y-5">
        <section className="clay-card space-y-4 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-bold"><Activity size={20} />Live health console</h2><p className="mt-1 text-xs text-muted">Database and school readings refresh every 30 seconds while this console is open.</p></div><button onClick={refresh} disabled={health.isFetching} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-50"><RefreshCw size={16} className={health.isFetching ? 'animate-spin' : ''} />{health.isFetching ? 'Checking…' : 'Refresh health'}</button></div>
            <p className="text-xs text-muted">Last successful check: {date(h?.checked_at)}{h && ` · Browser-to-database round trip ${h.roundtrip_ms} ms`}</p>
            {health.error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">Current readings unavailable: {health.error.message}. {h && 'The readings below are from the last successful check.'}</p>}
            <nav aria-label="Health console sections" className="flex flex-wrap gap-2">{['Overview', 'Schools', 'Database', 'Files & cache'].map(name => <button key={name} onClick={() => setSection(name)} aria-current={section === name ? 'page' : undefined} className={`rounded-lg px-3 py-2 text-sm font-semibold ${section === name ? 'bg-primary text-white' : 'bg-stone-100 text-stone-700'}`}>{name}</button>)}</nav>
        </section>
        {!h ? <p role="status" className="p-4 text-sm text-muted">{health.error ? 'Use Refresh health to retry.' : 'Reading connected services…'}</p> : <>
            {section === 'Overview' && <>
                <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Schools" value={count(h.schools)} /><Stat label="Active users" value={count(h.users)} /><Stat label="Database size" value={bytes(h.database.size_bytes)} used={h.database.size_bytes} total={dataVolume?.size_bytes} basis="Share of data volume capacity" unavailable="Data volume capacity unavailable" /><Stat label="Stored files" value={count(h.storage.status === 'available' ? h.storage.files : null)} hint={bytes(h.storage.status === 'available' ? h.storage.bytes : null)} basis="File storage filled" unavailable="Storage quota unavailable" /></div>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">Service checks</h3><div className="grid gap-3 sm:grid-cols-2"><Stat label="Database" value={h.database.status} hint={`${count(h.database.connections)} / ${count(h.database.max_connections)} connections`} used={h.database.connections} total={h.database.max_connections} basis="Connection capacity used" showRemaining /><Stat label="Storage catalog" value={h.storage.status} hint={h.storage.reason ?? 'Live object metadata'} /><Stat label="Metric scheduler" value={h.scheduler_enabled ? 'Running · every 5 minutes' : 'No active schedule'} hint={`Last metric refresh: ${date(h.metrics_updated_at)}`} /><Stat label="Alerts / errors in last hour" value={`${count(h.active_alerts)} / ${count(h.errors_last_hour)}`} /></div><Link to="/alerts" className="text-sm font-semibold text-primary underline">Review alerts and activity</Link></section>
                <section className="clay-card space-y-4 p-5 sm:p-7"><div><h3 className="text-lg font-bold">Database host resources</h3><p className="mt-1 text-xs text-muted">Supabase monitoring snapshot: {date(h.infrastructure?.measured_at)}. Collector runs locally every minute; readings become stale if it stops.</p></div>
                    {!h.infrastructure ? <p className="text-sm text-muted">No provider snapshot collected yet. CPU, RAM and disk readings are unavailable.</p> : <>{!h.infrastructure.fresh && <p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Provider readings are stale. Restart the monitoring collector before relying on these values.</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Stat label="CPU · measured interval" value={h.infrastructure.cpu_percent == null ? 'Awaiting two samples' : `${h.infrastructure.cpu_percent}%`} used={h.infrastructure.cpu_percent} total={100} basis="CPU utilization" unavailable="Awaiting two valid samples" /><Stat label="Memory used / total" value={`${bytes(h.infrastructure.memory_used_bytes)} / ${bytes(h.infrastructure.memory_total_bytes)}`} used={h.infrastructure.memory_used_bytes} total={h.infrastructure.memory_total_bytes} basis="RAM used" showRemaining /><Stat label="Memory available" value={bytes(h.infrastructure.memory_available_bytes)} used={h.infrastructure.memory_available_bytes} total={h.infrastructure.memory_total_bytes} basis="RAM available" /><Stat label="Host file cache" value={bytes(h.infrastructure.memory_cache_bytes)} used={h.infrastructure.memory_cache_bytes} total={h.infrastructure.memory_total_bytes} basis="Share of total RAM" /><Stat label="Host buffers" value={bytes(h.infrastructure.memory_buffers_bytes)} used={h.infrastructure.memory_buffers_bytes} total={h.infrastructure.memory_total_bytes} basis="Share of total RAM" /><Stat label="Load · 1 minute" value={count(h.infrastructure.load_1m)} /></div>
                        {h.infrastructure.filesystems.map(f => <div key={f.mount} className="rounded-xl border p-4 text-sm"><p className="font-semibold">{f.mount === '/data' ? 'Database data volume' : 'Host root volume'}</p><p className="mt-1 text-muted">Used {bytes(filesystemUsed(f.size_bytes, f.available_bytes))} · available {bytes(f.available_bytes)} / total {bytes(f.size_bytes)}</p><UsageMeter used={filesystemUsed(f.size_bytes, f.available_bytes)} total={f.size_bytes} basis="Volume filled" showRemaining /></div>)}
                        <div className="flex flex-wrap gap-2">{h.infrastructure.services?.map(s => <span key={s.name} className={`rounded-lg px-3 py-2 text-xs ${s.status === 'ACTIVE_HEALTHY' ? 'bg-teal-50 text-teal-900' : 'bg-amber-50 text-amber-900'}`}>{s.name}: {s.status}</span>)}</div></>}
                </section>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">App requests · last hour</h3><p className="text-xs text-muted">Measured by signed-in browsers, sent in 30-second batches. Excludes monitoring, auth, external clients and traffic that bypasses this app.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Reported requests" value={count(h.requests.requests)} /><Stat label="Failed HTTP / network requests" value={count(h.requests.failures)} used={h.requests.failures} total={h.requests.requests} basis="Share of measured requests" unavailable="No request samples" /><Stat label="Average measured response" value={ms(h.requests.average_ms)} /><Stat label="Reporting users" value={count(h.requests.reporting_users)} /></div><p className="text-xs text-muted">Last report: {date(h.requests.last_report_at)}. No samples means no measurement, rather than zero platform traffic.</p>{external('/reports/api', 'Open provider request reports')}</section>
                {h.recent_errors.length > 0 && <section className="clay-card space-y-3 p-5 sm:p-7"><h3 className="text-lg font-bold">Latest recorded errors</h3>{h.recent_errors.map((e, i) => <div key={i} className="rounded-lg border p-3 text-sm"><p className="font-semibold">{e.message}</p><p className="mt-1 text-xs text-muted">{e.school_name ?? 'Platform'} · {date(e.created_at)}</p></div>)}</section>}
            </>}
            {section === 'Schools' && <>
                <section className="clay-card space-y-4 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold">Each school</h3><input aria-label="Search schools in health console" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search schools" className="rounded-xl border px-3 py-2 text-sm" /></div><p className="text-xs text-muted">Current active account counts and attributed file usage. Requests are browser measurements from the last hour.</p>
                    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['School', 'Students', 'Teachers / staff', 'Classes', 'Files', 'Requests / failed', 'Inspect'].map(v => <th key={v} className={`${cell} whitespace-nowrap text-xs text-muted`}>{v}</th>)}</tr></thead><tbody>{h.school_details.filter(s => s.name.toLowerCase().includes(search.toLowerCase())).map(s => <tr key={s.id}><td className={cell}><strong>{s.name}</strong><p className="mt-1 text-xs text-muted">{s.status} · {s.subscription_status ?? 'No subscription status'}</p></td><td className={cell}>{count(s.students)}{s.student_limit != null && <span className="text-xs text-muted"> / {count(s.student_limit)}</span>}<UsageMeter used={s.students} total={s.student_limit} basis="Student allowance used" unavailable="No student allowance configured" /></td><td className={cell}>{count(s.teachers)} / {count(s.staff)}</td><td className={cell}>{count(s.classes)}</td><td className={cell}>{bytes(s.file_bytes)}<p className="text-xs text-muted">{count(s.files)} files</p><p className="mt-2 text-xs text-muted">School file quota unavailable</p></td><td className={cell}>{count(s.requests)} / {count(s.request_failures)}<UsageMeter used={s.request_failures} total={s.requests} basis="Request failure rate" unavailable="No request samples" /></td><td className={cell}><button onClick={() => setSchoolId(s.id)} className="font-semibold text-primary underline">Inspect {s.name}</button></td></tr>)}</tbody></table></div>{!h.school_details.length && <p className="text-sm text-muted">No schools to inspect.</p>}
                </section>
                {school && <section className="clay-card space-y-4 p-5 sm:p-7"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">{school.name} · school health</h3><button onClick={() => setSchoolId('')} className="text-sm underline">Close details</button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[['Active users', count(school.users)], ['Students', count(school.students)], ['Teachers', count(school.teachers)], ['Parents', count(school.parents)], ['Administrators', count(school.admins)], ['Staff records', count(school.staff)], ['Classes', count(school.classes)], ['Files', `${count(school.files)} · ${bytes(school.file_bytes)}`], ['AI access', school.ai_enabled ? 'Enabled' : 'Disabled'], ['Sign-ins · 24 hours', count(school.logins_24h)], ['Activity records · 24 hours', count(school.changes_24h)], ['Errors · 24 hours', count(school.errors_24h)]].map(([label, value]) => <Stat key={label} label={label} value={value} used={label === 'Students' ? school.students : undefined} total={label === 'Students' ? school.student_limit : undefined} basis={label === 'Students' ? 'Student allowance used' : label === 'Files' ? 'File storage filled' : undefined} unavailable={label === 'Files' ? 'School file quota unavailable' : 'No student allowance configured'} />)}</div><p className="text-xs text-muted">Last activity: {date(school.last_activity_at)} · Measured requests: {count(school.requests)} · Failures: {count(school.request_failures)} · Average: {ms(school.average_ms)}</p>
                    <h4 className="font-semibold">School database records</h4><p className="text-xs text-muted">On-demand row counts include historical/soft-deleted records. Logical row bytes exclude shared indexes, database free space, and provider files.</p>
                    {schoolDetail.error ? <p role="alert" className="text-sm text-rose-800">{schoolDetail.error.message}</p> : !schoolDetail.data ? <p role="status" className="text-sm">Measuring school records…</p> : <><p className="text-sm font-bold">Logical row data: {bytes(schoolDetail.data.logical_bytes)} · {date(schoolDetail.data.checked_at)}</p><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead><tr>{['Table', 'Rows', 'Logical bytes'].map(v => <th key={v} className={cell}>{v}</th>)}</tr></thead><tbody>{schoolDetail.data.tables.filter(t => t.rows > 0).map(t => <tr key={t.name}><td className={`${cell} font-mono text-xs`}>{t.name}</td><td className={cell}>{count(t.rows)}</td><td className={cell}>{bytes(t.logical_bytes)}<UsageMeter used={t.logical_bytes} total={schoolDetail.data?.logical_bytes} basis="Share of school row data" /></td></tr>)}</tbody></table></div></>}
                </section>}
            </>}
            {section === 'Database' && <>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">Database health</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Stat label="Database bytes" value={bytes(h.database.size_bytes)} used={h.database.size_bytes} total={dataVolume?.size_bytes} basis="Share of data volume capacity" unavailable="Data volume capacity unavailable" hint={h.infrastructure ? `Volume snapshot: ${date(h.infrastructure.measured_at)}${h.infrastructure.fresh ? '' : ' · stale'}. Includes no other databases or filesystem files.` : undefined} /><Stat label="Connections / maximum" value={`${count(h.database.connections)} / ${count(h.database.max_connections)}`} used={h.database.connections} total={h.database.max_connections} basis="Connection capacity used" showRemaining /><Stat label="Active connections" value={count(h.database.active_connections)} used={h.database.active_connections} total={h.database.connections} basis="Share of current connections" unavailable="No connection samples" /><Stat label="Idle in transaction" value={count(h.database.idle_in_transaction)} used={h.database.idle_in_transaction} total={h.database.connections} basis="Share of current connections" unavailable="No connection samples" /><Stat label="Waiting on locks" value={count(h.database.waiting_connections)} used={h.database.waiting_connections} total={h.database.connections} basis="Share of current connections" unavailable="No connection samples" /><Stat label="Buffer cache hit rate" value={h.database.cache_hit_percent == null ? 'No samples' : `${h.database.cache_hit_percent}%`} used={h.database.cache_hit_percent} total={100} basis="Reads served from cache" unavailable="No buffer read samples" /><Stat label="Committed transactions" value={count(h.database.commits)} /><Stat label="Rolled-back transactions" value={count(h.database.rollbacks)} used={h.database.rollbacks} total={h.database.commits + h.database.rollbacks} basis="Share of all transactions" unavailable="No transaction samples" /><Stat label="Deadlocks" value={count(h.database.deadlocks)} /></div><p className="text-xs text-muted">Transaction, cache and deadlock counters are cumulative. Statistics reset: {date(h.database.stats_reset_at)}. Server started: {date(h.database.database_started_at)}.</p>{external('/database/query-performance', 'Open database query performance')}</section>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">Largest application tables</h3><p className="text-xs text-muted">Physical bytes include indexes and auxiliary data. PostgreSQL row/dead-row statistics are estimates.</p><div className="max-h-[32rem] overflow-auto"><table className="w-full text-sm"><thead><tr>{['Table', 'Total bytes', 'Index bytes', 'Est. rows', 'Est. dead rows', 'Auto-vacuum'].map(v => <th key={v} className={`${cell} whitespace-nowrap`}>{v}</th>)}</tr></thead><tbody>{h.tables.map(t => <tr key={t.name}><td className={`${cell} font-mono text-xs`}>{t.name}</td><td className={cell}>{bytes(t.bytes)}<UsageMeter used={t.bytes} total={h.database.size_bytes} basis="Share of database" /></td><td className={cell}>{bytes(t.index_bytes)}<UsageMeter used={t.index_bytes} total={t.bytes} basis="Share of table size" /></td><td className={cell}>{count(t.estimated_rows)}</td><td className={cell}>{count(t.estimated_dead_rows)}</td><td className={`${cell} whitespace-nowrap text-xs`}>{date(t.last_autovacuum)}</td></tr>)}</tbody></table></div></section>
            </>}
            {section === 'Files & cache' && <>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">Stored files and uploads</h3>{h.storage.status !== 'available' ? <p className="text-sm text-muted">{h.storage.reason ?? 'Storage measurements are unavailable.'}</p> : <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Stat label="Files in storage catalog" value={count(h.storage.files)} /><Stat label="Known file bytes" value={bytes(h.storage.bytes)} basis="File storage filled" unavailable="Storage quota unavailable; open provider usage for your plan limit" /><Stat label="Files without recorded size" value={count(h.storage.unknown_size_files)} used={h.storage.unknown_size_files} total={h.storage.files} basis="Share of file catalog" unavailable="No stored files" /><Stat label="Platform / unattributed files" value={count(h.storage.unassigned_files)} hint={bytes(h.storage.unassigned_bytes)} used={h.storage.unassigned_bytes} total={h.storage.bytes} basis="Share of known file bytes" unavailable="No known file bytes" /><Stat label="Incomplete multipart uploads" value={count(h.storage.uploads?.count)} /><Stat label="In-progress uploaded bytes" value={bytes(h.storage.uploads?.bytes)} /></div><p className="text-xs text-muted">File sizes come from provider metadata. School attribution uses school folders, announcement ownership, then uploader school. Unattributed files stay separate. Missing sizes are excluded from byte totals.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Bucket', 'Access', 'Files', 'Known bytes', 'Per-file upload limit', 'Latest upload'].map(v => <th key={v} className={`${cell} whitespace-nowrap`}>{v}</th>)}</tr></thead><tbody>{h.storage.buckets.map(b => <tr key={b.id}><td className={cell}>{b.name}</td><td className={cell}>{b.public ? 'Public' : 'Private'}</td><td className={cell}>{count(b.files)}</td><td className={cell}>{bytes(b.bytes)}<UsageMeter used={b.bytes} total={h.storage.bytes} basis="Share of known file bytes" unavailable="No known file bytes" /></td><td className={cell}>{b.file_size_limit == null ? 'No bucket limit' : bytes(b.file_size_limit)}</td><td className={`${cell} text-xs`}>{date(b.last_upload_at)}</td></tr>)}</tbody></table></div></>}{external('/storage/buckets', 'Open file storage')} · {external('/settings/usage', 'Check provider usage limits')}</section>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">Cache and temporary database activity</h3><div className="grid gap-3 sm:grid-cols-2"><Stat label="Dashboard metric cache" value={bytes(h.cache.metric_bytes)} hint={`${count(h.cache.metric_rows)} cached metric rows`} used={h.cache.metric_bytes} total={h.database.size_bytes} basis="Share of database" /><Stat label="Request telemetry storage" value={bytes(h.cache.request_metric_bytes)} hint={`Retained for ${h.cache.request_retention_days} days`} used={h.cache.request_metric_bytes} total={h.database.size_bytes} basis="Share of database" /><Stat label="Temporary relations now" value={bytes(h.database.temporary_relation_bytes)} used={h.database.temporary_relation_bytes} total={h.database.size_bytes} basis="Share of database" /><Stat label="Temporary query files · cumulative" value={bytes(h.database.temp_bytes)} hint={`${count(h.database.temp_files)} files generated since statistics reset`} /></div><p className="text-xs text-muted">Cumulative temporary bytes are query spill volume over time, not current occupied disk space. Provider CDN cache bytes and per-school physical index allocation are unavailable.</p></section>
                <section className="clay-card space-y-4 p-5 sm:p-7"><h3 className="text-lg font-bold">This browser’s cache and storage</h3><p className="text-xs text-muted">Only this browser and site origin. Browser storage estimates are separate from server storage.</p>{browser.error ? <p role="alert" className="text-sm">Browser storage readings are unavailable.</p> : <div className="grid gap-3 sm:grid-cols-2"><Stat label="Origin storage estimate / quota" value={`${bytes(browser.data?.originBytes)} / ${bytes(browser.data?.quotaBytes)}`} used={browser.data?.originBytes} total={browser.data?.quotaBytes} basis="Browser origin quota used" showRemaining /><Stat label="Local storage · estimated bytes" value={bytes(browser.data?.localBytes)} /><Stat label="Session storage · estimated bytes" value={bytes(browser.data?.sessionBytes)} /><Stat label="Browser Cache API entries" value={count(browser.data?.cacheEntries)} /><Stat label="In-memory app query entries" value={queryClient.getQueryCache().getAll().length} /></div>}</section>
                <CacheCleanup cacheEntries={browser.data?.cacheEntries} onRefresh={refresh} />
            </>}
        </>}
    </div>;
}
